int num, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10;
Console.WriteLine("Inserte un numero entero: ");
num = int.Parse(Console.ReadLine());
x1 = num ;
x2 = num * 2;
x3 = num * 3;
x4 = num * 4;
x5 = num * 5;
x6 = num * 6;
x7 = num * 7;
x8 = num * 8;
x9 = num * 9;
x10 = num * 10;
Console.WriteLine("El num multiplicado x1 es: " + x1);
Console.WriteLine("El num multiplicado x2 es: " + x2);
Console.WriteLine("El num multiplicado x3 es: " + x3);
Console.WriteLine("El num multiplicado x4 es: " + x4);
Console.WriteLine("El num multiplicado x5 es: " + x5);
Console.WriteLine("El num multiplicado x6 es: " + x6);
Console.WriteLine("El num multiplicado x7 es: " + x7);
Console.WriteLine("El num multiplicado x8 es: " + x8);
Console.WriteLine("El num multiplicado x9es: " + x9);
Console.WriteLine("El num multiplicado x10 es: " + x10);
Console.ReadKey();  